runMyCode:
	echo "if test -f a.out; then" > runMyColorReversalCode.sh
	echo "	#echo \"File exists.\"" >> runMyColorReversalCode.sh
	echo "	rm a.out" >> runMyColorReversalCode.sh
	echo "else" >> runMyColorReversalCode.sh
	echo "	echo \"File does not exist.\"" >> runMyColorReversalCode.sh
	echo "fi" >> runMyColorReversalCode.sh
	echo "g++ colorReversal.cpp" >> runMyColorReversalCode.sh
	echo "./a.out" >> runMyColorReversalCode.sh
	clear
	bash runMyColorReversalCode.sh
